### ISSUE TITLE
MPS does not support cumsum op with int64 input

### ISSUE THREAD

**Issue by xuwu125** [xverse-ai/XVERSE-13B#15]
To create a public link, set `share=True` in `launch()`.
/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/site-packages/transformers/generation/utils.py:742: UserWarning: MPS: no support for int64 repeats mask, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Repeat.mm:236.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Exception in thread Thread-7 (generate):
Traceback (most recent call last):
  File "/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/site-packages/transformers/generation/utils.py", line 1618, in generate
    return self.sample(
  File "/Users/xxxx/.pyenv/versions/3.10.6/lib/python3.10/site-packages/transformers/generation/utils.py", line 2737, in sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/xxxx/.cache/huggingface/modules/transformers_modules/modeling_xverse.py", line 800, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input

请问如何解决，python ./chat_demo.py --port='8989' --model_path= 这种方式启动的，模型是下载的 https://huggingface.co/xverse/XVERSE-13B-Chat/tree/main

**Comment by xuwu125** [comment]
电脑是m2 芯片的

**Comment by underspirit** [comment]
这是pytorch算子支持的问题, 可以去pytorch社区查找相关解决方案, 比如 https://github.com/pytorch/pytorch/issues/96610
